apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: livestream-exporter
  name: livestream-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestream-exporter
  template:
    metadata:
      labels:
        app: livestream-exporter
    spec:
      containers:
        - image: busybox:latest
          imagePullPolicy: Always
          name: livestream-exporter
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              subPath: config.yaml
      imagePullSecrets:
        - name: ops-harbor-login-secret
      #nodeSelector:
      #  tier: app
      volumes:
        - name: config-volume
          secret:
            secretName: livestream-exporter
            items:
              - key: config.yaml
                path: config.yaml
