apiVersion: v1
kind: Service
metadata:
  labels:
    app: livestream-exporter
  name: livestream-exporter
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: livestream-exporter
  type: ClusterIP
